import { createHash } from "node:crypto";

export interface IdiomCandidate {
  id: string;
  text: string;
  pinyin: string[];
  head: string;
  tail: string;
  frequency: number;
  sourceRank: number;
  status: "NEEDS_MEANING";
  reviewFlags: ["PINYIN_UNVERIFIED", "MEANING_MISSING"];
}

export interface IdiomCandidateStats {
  sourceRecords: number;
  fourCharacterRecords: number;
  uniqueRecords: number;
  excludedExisting: number;
  available: number;
  output: number;
}

export interface IdiomCandidateManifest {
  schemaVersion: "idiom-candidates-v1";
  source: {
    name: "THUOCL";
    url: string;
    license: "MIT";
    licenseUrl: string;
    commit: string;
    sha256: string;
    fetchedAt: string;
  };
  generator: {
    command: string;
    pinyinProVersion: string;
    ranking: "frequency-desc-text-unicode-asc";
    fieldMapping: {
      text: "NFC-normalized THUOCL term";
      frequency: "maximum THUOCL DF for the normalized term";
      pinyin: "four trimmed syllables generated by pinyin-pro";
      head: "first Unicode code point of text";
      tail: "fourth Unicode code point of text";
      sourceRank: "one-based position after deterministic ranking";
      status: "fixed NEEDS_MEANING";
      reviewFlags: "fixed PINYIN_UNVERIFIED and MEANING_MISSING";
    };
  };
  inputs: { idiomBankSha256: string };
  stats: IdiomCandidateStats;
  output: { file: string; count: number; sha256: string };
}

export interface BuildIdiomCandidatesOptions {
  sourceText: string;
  existingTexts: ReadonlySet<string>;
  count: number;
  pinyinFor: (text: string) => string[];
}

export interface BuildIdiomCandidatesResult {
  candidates: IdiomCandidate[];
  stats: IdiomCandidateStats;
}

export interface BuildIdiomCandidateManifestOptions {
  sourceCommit: string;
  sourceSha256: string;
  bankSha256: string;
  outputSha256: string;
  fetchedAt: string;
  pinyinProVersion: string;
  count: number;
  stats: IdiomCandidateStats;
}

interface SourceRecord {
  text: string;
  frequency: number;
}

const FOUR_BASIC_CJK = /^[\u4E00-\u9FFF]{4}$/u;
const LOWERCASE_COMMIT = /^[0-9a-f]{40}$/;
const LOWERCASE_SHA256 = /^[0-9a-f]{64}$/;
const ISO_TIMESTAMP =
  /^\d{4}-\d{2}-\d{2}T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z|[+-](?:[01]\d|2[0-3]):[0-5]\d)$/;
const STAT_FIELDS = [
  "sourceRecords",
  "fourCharacterRecords",
  "uniqueRecords",
  "excludedExisting",
  "available",
  "output",
] as const;

const SOURCE_FILE = "data/THUOCL_chengyu.txt";
const OUTPUT_FILE = "idioms-thuocl-top1000.ndjson";
const GENERATOR_COMMAND =
  "pnpm exec tsx packages/content-cli/src/bin.ts idiom-candidates";

export function sha256Text(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

function compareCodePoints(left: string, right: string): number {
  // Accepted terms contain only BMP basic CJK characters, so UTF-16 and
  // Unicode code-point order are identical.
  return Number(left > right) - Number(left < right);
}

function parseSourceRecords(sourceText: string): SourceRecord[] {
  const lines = sourceText
    .split(/\r?\n/)
    .map((line, index) => ({ line, lineNumber: index + 1 }))
    .filter(({ line }) => line.trim().length > 0);

  return lines.map(({ line, lineNumber }) => {
    const fields = line.split("\t");
    if (fields.length !== 2) {
      throw new Error(
        `THUOCL line ${lineNumber}: expected <text>\\t<positive integer DF>`,
      );
    }

    const text = fields[0]!.normalize("NFC").trim();
    const frequencyText = fields[1]!.trim();
    const frequency = Number(frequencyText);
    if (
      !/^[0-9]+$/.test(frequencyText) ||
      !Number.isSafeInteger(frequency) ||
      frequency <= 0
    ) {
      throw new Error(
        `THUOCL line ${lineNumber}: expected <text>\\t<positive integer DF>`,
      );
    }
    return { text, frequency };
  });
}

export function buildIdiomCandidates(
  options: BuildIdiomCandidatesOptions,
): BuildIdiomCandidatesResult {
  if (!Number.isInteger(options.count) || options.count <= 0) {
    throw new Error("count must be a positive integer");
  }

  const sourceRecords = parseSourceRecords(options.sourceText);
  const fourCharacterRecords = sourceRecords.filter(({ text }) =>
    FOUR_BASIC_CJK.test(text),
  );
  const highestFrequencyByText = new Map<string, number>();
  for (const { text, frequency } of fourCharacterRecords) {
    highestFrequencyByText.set(
      text,
      Math.max(highestFrequencyByText.get(text) ?? frequency, frequency),
    );
  }

  const uniqueRecords = Array.from(
    highestFrequencyByText,
    ([text, frequency]) => ({ text, frequency }),
  );
  const normalizedExistingTexts = new Set(
    Array.from(options.existingTexts, (text) => text.normalize("NFC").trim()),
  );
  const availableRecords = uniqueRecords
    .filter(({ text }) => !normalizedExistingTexts.has(text))
    .sort(
      (left, right) =>
        right.frequency - left.frequency ||
        compareCodePoints(left.text, right.text),
    );

  if (availableRecords.length < options.count) {
    throw new Error(
      `requested ${options.count} candidates, only ${availableRecords.length} available`,
    );
  }

  const candidates = availableRecords
    .slice(0, options.count)
    .map<IdiomCandidate>(({ text, frequency }, index) => {
      const pinyin = options.pinyinFor(text).map((syllable) => syllable.trim());
      if (pinyin.length !== 4 || pinyin.some((syllable) => syllable.length === 0)) {
        throw new Error(`${text}: expected 4 pinyin syllables`);
      }
      const characters = Array.from(text);
      return {
        id: `idiom-candidate-${String(index + 1).padStart(4, "0")}`,
        text,
        pinyin,
        head: characters[0]!,
        tail: characters[3]!,
        frequency,
        sourceRank: index + 1,
        status: "NEEDS_MEANING",
        reviewFlags: ["PINYIN_UNVERIFIED", "MEANING_MISSING"],
      };
    });

  return {
    candidates,
    stats: {
      sourceRecords: sourceRecords.length,
      fourCharacterRecords: fourCharacterRecords.length,
      uniqueRecords: uniqueRecords.length,
      excludedExisting: uniqueRecords.length - availableRecords.length,
      available: availableRecords.length,
      output: candidates.length,
    },
  };
}

export function serializeIdiomCandidates(
  candidates: readonly IdiomCandidate[],
): string {
  return candidates.length === 0
    ? ""
    : `${candidates.map((candidate) => JSON.stringify(candidate)).join("\n")}\n`;
}

export function buildIdiomCandidateManifest(
  options: BuildIdiomCandidateManifestOptions,
): IdiomCandidateManifest {
  if (!LOWERCASE_COMMIT.test(options.sourceCommit)) {
    throw new Error("sourceCommit must be a 40-character lowercase hex string");
  }
  for (const [field, value] of [
    ["sourceSha256", options.sourceSha256],
    ["bankSha256", options.bankSha256],
    ["outputSha256", options.outputSha256],
  ] as const) {
    if (!LOWERCASE_SHA256.test(value)) {
      throw new Error(`${field} must be a 64-character lowercase hex string`);
    }
  }

  const datePart = options.fetchedAt.slice(0, 10);
  const parsedFetchedAt = new Date(options.fetchedAt);
  const parsedDatePart = new Date(`${datePart}T00:00:00.000Z`);
  if (
    !ISO_TIMESTAMP.test(options.fetchedAt) ||
    Number.isNaN(parsedFetchedAt.valueOf()) ||
    parsedDatePart.toISOString().slice(0, 10) !== datePart
  ) {
    throw new Error("fetchedAt must be a valid ISO timestamp");
  }
  if (options.pinyinProVersion.trim().length === 0) {
    throw new Error("pinyinProVersion must not be empty");
  }
  if (!Number.isSafeInteger(options.count) || options.count <= 0) {
    throw new Error("count must be a positive safe integer");
  }
  for (const field of STAT_FIELDS) {
    if (
      !Number.isSafeInteger(options.stats[field]) ||
      options.stats[field] < 0
    ) {
      throw new Error(`${field} must be a non-negative safe integer`);
    }
  }
  if (options.stats.sourceRecords < options.stats.fourCharacterRecords) {
    throw new Error(
      "sourceRecords must be greater than or equal to fourCharacterRecords",
    );
  }
  if (options.stats.fourCharacterRecords < options.stats.uniqueRecords) {
    throw new Error(
      "fourCharacterRecords must be greater than or equal to uniqueRecords",
    );
  }
  if (options.stats.excludedExisting > options.stats.uniqueRecords) {
    throw new Error(
      "excludedExisting must be less than or equal to uniqueRecords",
    );
  }
  if (
    options.stats.available !==
    options.stats.uniqueRecords - options.stats.excludedExisting
  ) {
    throw new Error(
      "available must equal uniqueRecords minus excludedExisting",
    );
  }
  if (options.stats.available < options.stats.output) {
    throw new Error("available must be greater than or equal to output");
  }
  if (options.count !== options.stats.output) {
    throw new Error("count must match stats.output");
  }

  return {
    schemaVersion: "idiom-candidates-v1",
    source: {
      name: "THUOCL",
      url: `https://raw.githubusercontent.com/thunlp/THUOCL/${options.sourceCommit}/${SOURCE_FILE}`,
      license: "MIT",
      licenseUrl: `https://github.com/thunlp/THUOCL/blob/${options.sourceCommit}/LICENSE`,
      commit: options.sourceCommit,
      sha256: options.sourceSha256,
      fetchedAt: options.fetchedAt,
    },
    generator: {
      command: GENERATOR_COMMAND,
      pinyinProVersion: options.pinyinProVersion,
      ranking: "frequency-desc-text-unicode-asc",
      fieldMapping: {
        text: "NFC-normalized THUOCL term",
        frequency: "maximum THUOCL DF for the normalized term",
        pinyin: "four trimmed syllables generated by pinyin-pro",
        head: "first Unicode code point of text",
        tail: "fourth Unicode code point of text",
        sourceRank: "one-based position after deterministic ranking",
        status: "fixed NEEDS_MEANING",
        reviewFlags: "fixed PINYIN_UNVERIFIED and MEANING_MISSING",
      },
    },
    inputs: { idiomBankSha256: options.bankSha256 },
    stats: options.stats,
    output: {
      file: OUTPUT_FILE,
      count: options.count,
      sha256: options.outputSha256,
    },
  };
}
